#!/bin/bash

SRCDIR="src"
OUTDIR="pdf"
TMPDIR="tmp"


mk_pdf() {
	local	DIR;
	local	NAME;
	local	SRCNAME;
	local	FONAME;
	local	OUTNAME;

	DIR="$1"
	NAME="$2"

	SRCNAME="${SRCDIR}/${DIR}/${NAME}.xml"
	FONAME="${TMPDIR}/${DIR}-${NAME}.fo"
	OUTNAME="${OUTDIR}/${DIR}-${NAME}.pdf"

	mkdir -p ${TMPDIR}
	mkdir -p ${OUTDIR}

	if [ -f ${SRCNAME} ] ; then
		fop -xsl BGChess.xsl -xml ${SRCNAME} -foout ${FONAME} &&
		fop -c ./fop.xconf -fo ${FONAME} -pdf ${OUTNAME}
	else
		echo "Src file '${SRCNAME}' not found!"
	fi
}

#mk_pdf BGM12KP200
#mk_pdf BGK12

for i in 10 30 70 80 90 xx ; do
	mk_pdf BG12Zhuk KP${i}-split
	mk_pdf BG12Zhuk KP${i}-unite
done

for i in 510 520 ; do
	mk_pdf BG12Zhuk KP${i}
done
